# Generated by Django 3.2.24 on 2024-02-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (3, 'STUDENT'), (1, 'HOD')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Staff_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='DEFAULT VALUE', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('staff_id', models.ForeignKey(blank=True, default='DEFAULT VALUE', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
        ),
    ]
