# Generated by Django 3.2.24 on 2024-02-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240227_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STAFF'), (1, 'HOD'), (3, 'STUDENT')], default=1, max_length=50),
        ),
    ]
