# Generated by Django 3.2.24 on 2024-02-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20240227_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'STUDENT'), (1, 'HOD'), (2, 'STAFF')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='staff_feedback',
            name='feedback_reply',
            field=models.TextField(null=True),
        ),
    ]
